feat - Support React-style children
nicojs/typed-html pull request #16
Opened 2020-08-16 18:10 UTC by bebraw

After using **typed-html** a while at [tailwind-webpack-starter](https://github.com/survivejs/tailwind-webpack-starter), I started missing React-style `children` as that would simplify some of the code and make it feel more familiar.

I see my editor applied some formatting changes to the code. I can revert those if you prefer. I guess ideally we would have Prettier set up in the project as that would solve these kind of problems.

2020-09-01 16:38 UTC, marcj commented
@bebraw awesome! Exactly what is missing to build something more serious. @nicojs are you interested in merging this?

2020-09-01 16:47 UTC, bebraw commented
@marcj This might need more work and tuning but it's definitely worth a look.

One question is, should we simply drop the old syntax where contents are passed as the second parameter and go straight with React-style for `children`?

Another question is, should we support React-style fragments as well? My understanding is that this should be fairly simple (another field in configuration).

2020-09-01 17:41 UTC, nicojs commented
>I see my editor applied some formatting changes to the code. I can revert those if you prefer. I guess ideally we would have Prettier set up in the project as that would solve these kind of problems.

Yeah, planning to do that. You're forgiven for now 😉

2020-09-01 17:44 UTC, nicojs requested changes
Great, I think I get the gist of this. Please change these things and then it should be good.

2020-09-01 17:44 UTC, nicojs commented on CHANGELOG.md
> +* Support React-style `children` within `elements.Attributes`.
changelog is auto generated, please revert this change.

2020-09-01 17:44 UTC, nicojs commented on src/elements.tsx
> +export type Children = {
Please define this as an `interface`

2020-09-01 17:50 UTC, marcj commented
@bebraw If you ask me, then yes and yes. :) But it's of course up to @nicojs. 
I'd love to integrate this lib into a new server framework that would use this as template engine, so the more features it has that are required for "serious" apps, the better. 😅

2020-09-01 22:18 UTC, marcj commented
Oh nevermind, I just saw this does not have a OSS license. @nicojs do you plan to make this OSS?

2020-09-02 04:41 UTC, nicojs commented
Yes, should have Apache-2. PRs welcome :)

2020-09-08 09:30 UTC, bebraw commented
@nicojs I did the changes (sorry for the delay 😄 ).

I would probably drop the old way of handling `children` altogether and go with React-style as that's kind of standard but that's up to you.

2021-07-30 08:37 UTC, bebraw commented
Any thoughts on this? Should we finish up the PR?

2021-07-30 11:28 UTC, merged